name: "Build"

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true
      - name: Build
        run: |
          sudo apt-get update -y && sudo apt-get install -y wget unzip file git openjdk-17-jdk
          git submodule foreach git submodule update --init
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          mkdir sdk
          unzip -d sdk commandlinetools-linux-11076708_latest.zip
          export ANDROID_HOME=`pwd`/sdk
          export ANDROID_SDK_ROOT=`pwd`/sdk
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          yes | sdk/cmdline-tools/bin/sdkmanager --sdk_root=`pwd`/sdk --licenses
          ./gradlew assembleRelease
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            ref_name="pr-${{ github.event.pull_request.number }}"
          else
            ref_name="${{ github.ref_name }}"
          fi
          echo "ref_name=${ref_name}" >> $GITHUB_ENV

      # Create release
      - name: Generate release tag
        id: tag
        run: |
          sudo timedatectl set-timezone Asia/Ho_Chi_Minh
          sudo date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z"
          echo "release_tag=ActionBuild_$(date +"%Y.%m.%d_%H-%M-%S")" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            ./app/build/outputs/apk/release/hev.sockstun-*-release.apk
      # Done release

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
